const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "SWAGGER API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [],
    securityDefinitions: {
        bearerAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "Authorization",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        ExamplePayload :{
            name: "",
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app.js']
if (process.env.NODE_ENV === 'development') {
    doc.host="localhost:" + process.env.LISTEN_PORT
} else {
    /*
    TODO : here your IP server or domain
     */
    doc.host="xxx.xxx.xxx.xxx:3200"
}
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})
